# Generated by Django 3.0.8 on 2020-08-27 10:13

import uuid

import django.db.models.deletion
from django.db import migrations, models

import smart_meter.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField()),
                ('gas_import', models.DecimalField(decimal_places=3, max_digits=9)),
                ('duration', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('public_key',
                 models.SlugField(default=smart_meter.models.default_public_key, max_length=40, unique=True)),
                ('invitation_key', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('left_on', models.DateTimeField(default=None, null=True)),
                ('display_name', models.CharField(max_length=30)),
                ('power_import_joined', models.DecimalField(decimal_places=3, max_digits=9)),
                ('power_export_joined', models.DecimalField(decimal_places=3, max_digits=9)),
                ('gas_import_joined', models.DecimalField(decimal_places=3, max_digits=9)),
                ('power_import_left', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('power_export_left', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('gas_import_left', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField()),
                ('tariff', models.SmallIntegerField(editable=False)),
                ('power_import', models.DecimalField(decimal_places=3, max_digits=9)),
                ('power_export', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('public', models.BooleanField(default=False)),
                ('gpx_version', models.CharField(max_length=5)),
                ('last_update', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('sn_power', models.CharField(max_length=255, unique=True)),
                ('sn_gas', models.CharField(max_length=255, unique=True)),
                ('power_import_1', models.DecimalField(decimal_places=3, max_digits=9)),
                ('power_import_2', models.DecimalField(decimal_places=3, max_digits=9)),
                ('power_export_1', models.DecimalField(decimal_places=3, max_digits=9)),
                ('power_export_2', models.DecimalField(decimal_places=3, max_digits=9)),
                ('gas', models.DecimalField(decimal_places=3, max_digits=9)),
                ('solar', models.DecimalField(decimal_places=3, max_digits=9)),
                ('tariff', models.SmallIntegerField()),
                ('current_power_import', models.DecimalField(decimal_places=3, max_digits=9)),
                ('current_power_export', models.DecimalField(decimal_places=3, max_digits=9)),
                ('current_gas', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='SolarMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField()),
                ('solar_export', models.DecimalField(decimal_places=3, max_digits=9)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_meter.SmartMeter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
