# Generated by Django 3.0.8 on 2020-08-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('smart_meter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_meter.SmartMeter'),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants',
                                    to='smart_meter.GroupMeter'),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_participation',
                                    to='smart_meter.SmartMeter'),
        ),
        migrations.AddField(
            model_name='groupmeter',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_groups',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmeter',
            name='meters',
            field=models.ManyToManyField(related_name='groups', through='smart_meter.GroupParticipant',
                                         to='smart_meter.SmartMeter'),
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_meter.SmartMeter'),
        ),
        migrations.AlterUniqueTogether(
            name='solarmeasurement',
            unique_together={('meter', 'moment')},
        ),
        migrations.AlterUniqueTogether(
            name='powermeasurement',
            unique_together={('meter', 'moment')},
        ),
        migrations.AlterUniqueTogether(
            name='gasmeasurement',
            unique_together={('meter', 'moment')},
        ),
    ]
