# Generated by Django 3.0.8 on 2020-09-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0002_auto_20200827_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasmeasurement',
            old_name='moment',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='powermeasurement',
            old_name='moment',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='current_power_export',
            new_name='actual_power_export',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='current_power_import',
            new_name='actual_power_import',
        ),
        migrations.RenameField(
            model_name='solarmeasurement',
            old_name='moment',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='smartmeter',
            name='current_gas',
        ),
        migrations.RemoveField(
            model_name='smartmeter',
            name='version',
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='gas_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='smartmeter',
            name='gas',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='smartmeter',
            name='gpx_version',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='smartmeter',
            name='sn_gas',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='smartmeter',
            name='sn_power',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='smartmeter',
            name='solar',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gasmeasurement',
            unique_together={('meter', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='powermeasurement',
            unique_together={('meter', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='solarmeasurement',
            unique_together={('meter', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='powermeasurement',
            name='tariff',
        ),
    ]
