# Generated by Django 3.0.8 on 2020-09-21 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0003_auto_20200921_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartmeter',
            old_name='last_update',
            new_name='power_timestamp',
        ),
    ]
