# Generated by Django 3.0.8 on 2020-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0005_auto_20200922_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmeter',
            name='sn_gas',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
