# Generated by Django 3.0.8 on 2020-09-23 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0007_auto_20200923_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasmeasurement',
            name='duration',
        ),
    ]
