# Generated by Django 3.0.8 on 2020-10-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0009_smartmeter_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupparticipant',
            old_name='gas_import_joined',
            new_name='gas_joined',
        ),
        migrations.RenameField(
            model_name='groupparticipant',
            old_name='gas_import_left',
            new_name='gas_left',
        ),
        migrations.AlterField(
            model_name='groupparticipant',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_participations',
                                    to='smart_meter.SmartMeter'),
        ),
    ]
