# Generated by Django 3.0.8 on 2020-10-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0010_auto_20201004_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmeter',
            name='allow_invite',
            field=models.BooleanField(default=True),
        ),
    ]
