# Generated by Django 3.0.8 on 2020-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0011_groupmeter_allow_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasmeasurement',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
