# Generated by Django 3.0.8 on 2020-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0012_gasmeasurement_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmeter',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
