# Generated by Django 3.0.8 on 2020-11-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0013_groupmeter_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupparticipant',
            name='gas_joined',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
    ]
