# Generated by Django 3.0.8 on 2020-11-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('smart_meter', '0014_auto_20201113_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartmeter',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
