# Generated by Django 3.0.8 on 2020-12-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0015_auto_20201114_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='type',
            field=models.CharField(choices=[('consumer', 'Consument'), ('prosumer', 'Prosument'), ('battery', 'Batterij'), ('producer_solar', 'Producent solar'), ('producer_wind', 'Producent wind'), ('producer_other', 'Producent wind')], default='consumer', max_length=20),
        ),
    ]
