# Generated by Django 3.0.8 on 2021-03-10 17:23

from django.db import migrations, models


def delete_gas_measurements(apps, schema_editor):
    GasMeasurement = apps.get_model("smart_meter", "GasMeasurement")
    GasMeasurement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0017_auto_20210105_1028'),
    ]

    operations = [
        migrations.RunPython(delete_gas_measurements),
        migrations.RenameField(
            model_name='powermeasurement',
            old_name='power_exp',
            new_name='actual_export',
        ),
        migrations.RenameField(
            model_name='powermeasurement',
            old_name='power_imp',
            new_name='actual_import',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='solar',
            new_name='actual_solar',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='gas',
            new_name='total_gas',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='power_export_1',
            new_name='total_power_export_1',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='power_export_2',
            new_name='total_power_export_2',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='power_import_1',
            new_name='total_power_import_1',
        ),
        migrations.RenameField(
            model_name='smartmeter',
            old_name='power_import_2',
            new_name='total_power_import_2',
        ),
        migrations.RenameField(
            model_name='solarmeasurement',
            old_name='solar',
            new_name='actual_solar',
        ),
        migrations.RemoveField(
            model_name='gasmeasurement',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='gasmeasurement',
            name='total',
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='actual_gas',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasmeasurement',
            name='total_gas',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='solar_joined',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='groupparticipant',
            name='solar_left',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='total_export_1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='total_export_2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='total_import_1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powermeasurement',
            name='total_import_2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='actual_gas',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='total_solar',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='solarmeasurement',
            name='total_solar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
