# Generated by Django 3.0.8 on 2021-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0018_auto_20210310_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartmeter',
            name='public',
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='visibility_type',
            field=models.CharField(choices=[('private', 'Privé'), ('group', 'Groep'), ('public', 'Publiek')], default='private', max_length=10),
        ),
    ]
