# Generated by Django 3.0.8 on 2022-10-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_meter', '0019_auto_20210317_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartmeter',
            name='residence_energy_label',
            field=models.CharField(choices=[('undefined', 'Onbekend'), ('apppp', 'A++++'), ('appp', 'A+++'), ('app', 'A++'), ('ap', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], default='undefined', max_length=10),
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='residence_type',
            field=models.CharField(choices=[('undefined', 'Onbekend'), ('apartment', 'Appartement'), ('corner_house', 'Hoekwoning'), ('terraced_house', 'Tussenwoning'), ('two_one_roof', 'Twee onder één kap'), ('detached_house', 'Vrijstaande woning'), ('ground_floor_apartment', 'Benedenwoning'), ('upstairs_apartment', 'Bovenwoning')], default='undefined', max_length=30),
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='resident_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='solar_panel_count',
            field=models.IntegerField(default=0),
        ),
    ]
