# Generated by Django 3.0.8 on 2020-09-21 11:50

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_user_default_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default=users.models.api_key_gen, max_length=20, unique=True),
        ),
    ]
